language: node_js
node_js:
  - 14
notifications:
  email: false
cache:
  yarn: true
jobs:
  include:
    - stage: build
      node_js: node
      script: yarn build
      env: Build debug & release
    - stage: test
      script: yarn test:ci
      env: Tests
