language: node_js
node_js:
  - '12'
notifications:
  email: false
cache: yarn
jobs:
  include:
    - stage: build
      node_js: node
      script: yarn run build
      env: Build debug & release
    - stage: test
      script: yarn run test:ci
      env: Tests
