name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: "${{ matrix.os }}, node ${{ matrix.node_version }}"
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: ["lts/*", "latest"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          check-latest: true
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Test sources
        run: yarn test:ci
